global_analysis = {
    "tonic": "Eb",
    "mode": "Ionian",
    "explanation": "La progression est globalement en Mi bémol majeur, comme l'indique l'accord d'ouverture (corrigé en Ebmaj7). Elle se caractérise par une série de modulations et de tonicisations intelligentes, utilisant des cadences claires pour voyager à travers différents centres tonaux avant de conclure sur une modulation inattendue.",
}
harmonic_segments = [
    {
        "start_index": 0,
        "end_index": 2,
        "tonic": "G",
        "mode": "Mixolydian",
        "explanation": "Ce segment établit Sol comme un centre tonal passager. En corrigeant D#maj7 en Ebmaj7, l'analyse révèle une cadence de type bVI-V-I (Ebmaj7 - D7sus4 - G7) en Sol Mixolydien. L'accord G7 final sert de pivot, fonctionnant comme la dominante de Do mineur (V7/vi dans la tonalité globale) pour se connecter au segment suivant.",
    },
    {
        "start_index": 3,
        "end_index": 5,
        "tonic": "Bb",
        "mode": "Ionian",
        "explanation": "Une cadence ii-V-I classique (Cm7 - F7 - Bbmaj7) qui établit fermement Si bémol majeur c                                   omme nouveau centre tonal. En corrigeant A#maj7 en Bbmaj7, la fonction de ce seg                                   ment comme tonicisation du Vème degré de Mi bémol majeur devient évidente. Le Cm                                   7 est un excellent accord pivot, servant de résolution au G7 précédent et de ii7                                    dans cette nouvelle tonalité.",
    },
    {
        "start_index": 6,
        "end_index": 7,
        "tonic": "A",
        "mode": "Harmonic Minor",
        "explanation": "La progression se termine par une modulation abrupte mais efficace vers La mineur. Elle est établie par une cadence parfaite V-i puissante (E7 - Am7). La transition depuis l'accord précédent (Bbmaj7) est un saut de médiante chromatique, une technique sophistiquée pour changer de tonalité de manière audacieuse.",
    },
]

quality_analysis = [
    {
        "chord": "D#maj7",
        "found_numeral": "bVImaj7",
        "expected_numeral": "bVImaj7",
        "found_quality": "maj7",
        "expected_quality": "maj7",
        "expected_chord_name": "Ebmaj7",
        "is_diatonic": False,
        "segment_context": {
            "tonic": "G",
            "mode": "Mixolydian",
            "explanation": "Ce segment établit Sol comme un centre tonal passager. En corrigeant D#maj7 en Ebmaj7, l'analyse révèle une cadence de type bVI-V-I (Ebmaj7 - D7sus4 - G7) en Sol Mixolydien. L'accord G7 final sert de pivot, fonctionnant comme la dominante de Do mineur (V7/vi dans la tonalité globale) pour se connecter au segment suivant.",
        },
    },
    {
        "chord": "D7sus4",
        "found_numeral": "V",
        "expected_numeral": "v7",
        "found_quality": "7sus4",
        "expected_quality": "m7",
        "expected_chord_name": "Dm7",
        "is_diatonic": True,
        "segment_context": {
            "tonic": "G",
            "mode": "Mixolydian",
            "explanation": "Ce segment établit Sol comme un centre tonal passager. En corrigeant D#maj7 en Ebmaj7, l'analyse révèle une cadence de type bVI-V-I (Ebmaj7 - D7sus4 - G7) en Sol Mixolydien. L'accord G7 final sert de pivot, fonctionnant comme la dominante de Do mineur (V7/vi dans la tonalité globale) pour se connecter au segment suivant.",
        },
    },
    {
        "chord": "G7",
        "found_numeral": "I7",
        "expected_numeral": "I7",
        "found_quality": "                                                           7",
        "expected_quality": "7",
        "expected_chord_name": "G7",
        "is_diatonic": True,
        "segment_context": {
            "tonic": "G",
            "mode": "Mixolydian",
            "explanation": "Ce segment établit Sol comme un centre tonal passager. En corrigeant D#maj7 en Ebmaj7, l'analyse révèle une cadence de type bVI-V-I (Ebmaj7 - D7sus4 - G7) en Sol Mixolydien. L'accord G7 final sert de pivot, fonctionnant comme la dominante de Do mineur (V7/vi dans la tonalité globale) pour se connecter au segment suivant.",
        },
    },
    {
        "chord": "Cm7",
        "found_numeral": "ii7",
        "expected_numeral": "ii7",
        "found_quality": "m7",
        "expected_quality": "m7",
        "expected_chord_name": "Cm7",
        "is_diatonic": True,
        "segment_context": {
            "tonic": "Bb",
            "mode": "Ionian",
            "explanation": "Une cadence ii-V-I classique (Cm7 - F7 - Bbmaj7) qui établit fermement Si bémol majeur comme nouveau centre tonal. En corrigeant A#maj7 en Bbmaj7, la fonction de ce segment comme tonicisation du Vème degré de Mi bémol majeur devient évidente. Le Cm7 est un excellent accord pivot, servant de résolution au G7 précédent et de ii7 dans cette nouvelle tonalité.",
        },
    },
    {
        "chord": "F7",
        "found_numeral": "V7",
        "expected_numeral": "V7",
        "found_quality": "7",
        "expected_quality": "7",
        "expected_chord_name": "F7",
        "is_diatonic": True,
        "segment_context": {
            "tonic": "Bb",
            "mode": "Ionian",
            "explanation": "Une cadence ii-V-I classique (Cm7 - F7 - Bbmaj7) qui établit fermement Si bémol majeur comme nouveau centre tonal. En corrigeant A#maj7 en Bbmaj7, la fonction de ce segment comme tonicisation du Vème degré de Mi bémol majeur devient évidente. Le Cm7 est un excellent accord pivot, servant de résolution au G7 précédent et de ii7 dans cette nouvelle tonalité.",
        },
    },
    {
        "chord": "A#maj7",
        "found_numeral": "Imaj7",
        "expected_numeral": "Imaj7",
        "found_quality": "maj7",
        "expected_quality": "maj7",
        "expected_chord_name": "A#maj7",
        "is_diatonic": True,
        "segment_context": {
            "tonic": "Bb",
            "mode": "Ionian",
            "explanation": "Une cadence ii-V-I classique (Cm7 - F7 - Bbmaj7) qui établit fermement Si bémol majeur comme nouveau centre tonal. En corrigeant A#maj7 en Bbmaj7, la fonction de ce segment comme tonicisation du Vème degré de Mi bémol majeur devient évidente. Le Cm7 est un excellent accord pivot, servant de résolution au G7 précédent et de ii7 dans cette nouvelle tonalité.",
        },
    },
    {
        "chord": "E7",
        "found_numeral": "                                                           V7",
        "expected_numeral": "V7",
        "found_quality": "7",
        "expected_quality": "7",
        "expected_chord_name": "E7",
        "is_diatonic": True,
        "segment_context": {
            "tonic": "A",
            "mode": "Harmonic Minor",
            "explanation": "La progression se termine par une modulation abrupte mais efficace vers La mineur. Elle est établie par une cadence parfaite V-i puissante (E7 - Am7). La transition depuis l'accord précédent (Bbmaj7) est un saut de médiante chromatique, une technique sophistiquée pour changer de tonalité de manière audacieuse.",
        },
    },
    {
        "chord": "Am7",
        "found_numeral": "i7",
        "expected_numeral": "im(maj7)",
        "found_quality": "m7",
        "expected_quality": "m(maj7)",
        "expected_chord_name": "Am(maj7)",
        "is_diatonic": False,
        "segment_context": {
            "tonic": "A",
            "mode": "Harmonic Minor",
            "explanation": "La progression se termine par une modulation abrupte mais efficace vers La mineur. Elle est établie par une cadence parfaite V-i puissante (E7 - Am7). La transition depuis l'accord précédent (Bbmaj7) est un saut de médiante chromatique, une technique sophistiquée pour changer de tonalité de manière audacieuse.",
        },
    },
]
